apiVersion: v2
name: bulk-data-export-client
description: A Helm chart for the Bulk Data Export Client Demo application
type: application
version: 0.1.0
appVersion: "0.0.0"
keywords:
  - fhir
  - bulk-export
  - vue
  - healthcare
maintainers:
  - name: John Grimes
home: https://github.com/gri306/bulk-data-export-client-demo