bulkDataExportClient:
  image: "bulk-data-export-client-demo:latest"
  imagePullPolicy: "IfNotPresent"
  replicas: 1

  resources: {}
    # requests:
    #   memory: "128Mi"
    #   cpu: "100m"
    # limits:
    #   memory: "256Mi"
    #   cpu: "200m"

  service:
    type: "ClusterIP"
    port: 80
    targetPort: 80

  healthCheck:
    enabled: true
    path: "/health"
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

  nodeSelector: {}

  tolerations: []

  affinity: {}
